lte(iv00, iv20) :- N(iv00, "Z", iv10), N(iv20, "Z", iv30).
lte(iv40, iv50) :- N(iv40, "S", x0), N(iv50, "S", y0), lte(x0, y0).
lte(x0, iv60) :- N(iv60, "S", y0), lte(x0, y0).
two_less_than_equal_to_two() :- N(iv70, "S", iv80), N(iv80, "S", iv90), N(iv90, "Z", iv100), N(iv110, "S", iv120), N(iv120, "S", iv130), N(iv130, "S", iv140), N(iv140, "S", iv150), N(iv150, "Z", iv160), lte(iv70, iv110).
four_less_than_equal_to_two() :- N(iv170, "S", iv180), N(iv180, "S", iv190), N(iv190, "S", iv200), N(iv200, "S", iv210), N(iv210, "Z", iv220), N(iv230, "S", iv240), N(iv240, "S", iv250), N(iv250, "Z", iv260), lte(iv170, iv230).
x_less_than_equal_to_x_plus_two() :- N(iv270, "S", iv280), N(iv280, "S", x0), lte(x0, iv270).