N(#0, "Z", iv10).
lte(iv20, iv40) :- N(iv20, "Z", iv30), N(iv40, "Z", iv50).
lte(iv60, iv70) :- N(iv60, "S", x0), N(iv70, "S", y0), lte(x0, y0).
lte(x0, iv80) :- N(iv80, "S", y0), lte(x0, y0).
two_less_than_equal_to_two() :- N(iv90, "S", iv100), N(iv100, "S", iv110), N(iv110, "Z", iv120), N(iv130, "S", iv140), N(iv140, "S", iv150), N(iv150, "S", iv160), N(iv160, "S", iv170), N(iv170, "Z", iv180), lte(iv90, iv130).
four_less_than_equal_to_two() :- N(iv190, "S", iv200), N(iv200, "S", iv210), N(iv210, "S", iv220), N(iv220, "S", iv230), N(iv230, "Z", iv240), N(iv250, "S", iv260), N(iv260, "S", iv270), N(iv270, "Z", iv280), lte(iv190, iv250).
x_less_than_equal_to_x_plus_two() :- N(iv290, "S", iv300), N(iv300, "S", x0), lte(x0, iv290).